[versions]
exoplayer = "2.19.1"
kotlin = "1.9.22"
workRuntimeKtx = "2.9.1"

[libraries]
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workRuntimeKtx" }
exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }

[plugins]
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

